#!/bin/bash

subj=FOSS_proc
afni_proc.py -subj_id ${subj} \
-dsets FOSS1.nii FOSS2.nii \
-blocks align volreg blur mask regress \
-volreg_base_dset FOSS1.nii'[0]'     \
-volreg_align_e2a                         \
-align_opts_aea -giant_move               \
-copy_anat SVol@Epi+orig.               \
-regress_censor_motion 0.5                \
-regress_censor_outliers 0.1              \
-blur_size 5

tcsh -xef proc.${subj} |& tee output.proc.${subj}
cd ./${subj}.results

# Detrend
run=( 01 02 )
for i in "${run[@]}"
do
3dDetrend -polort 2 -prefix pb02.${subj}.r$i.detrended+orig pb02.${subj}.r$i.blur+orig
done

# Regress
3dDeconvolve -input pb02.${subj}.r*.detrended+orig.HEAD                        \
    -censor censor_${subj}_combined_2.1D                                    \
    -polort 3                                                               \
    -num_stimts 10                                                          \
    -stim_file 1 motion_demean.1D'[0]' -stim_base 1 -stim_label 1 roll      \
    -stim_file 2 motion_demean.1D'[1]' -stim_base 2 -stim_label 2 pitch     \
    -stim_file 3 motion_demean.1D'[2]' -stim_base 3 -stim_label 3 yaw       \
    -stim_file 4 motion_demean.1D'[3]' -stim_base 4 -stim_label 4 dS        \
    -stim_file 5 motion_demean.1D'[4]' -stim_base 5 -stim_label 5 dL     \
    -stim_file 6 motion_demean.1D'[5]' -stim_base 6 -stim_label 6 dP     \
    -stim_times 7 ${RET_DIR}/Stim_files/face.txt 'BLOCK(14,1)'  \
    -stim_label 7 face \
    -stim_times 8 ${RET_DIR}/Stim_files/object.txt 'BLOCK(14,1)'\
    -stim_label 8 object \
    -stim_times 9 ${RET_DIR}/Stim_files/place.txt 'BLOCK(14,1)' \
    -stim_label 9 place \
    -stim_times 10 ${RET_DIR}/Stim_files/scram.txt 'BLOCK(14,1)' \
    -stim_label 10 scram \
    -local_times \
    -gltsym 'SYM: +1*face -1*object' \
    -glt_label 1 face-object \
    -gltsym 'SYM: +1*place -1*object' \
    -glt_label 2 place-object \
    -gltsym 'SYM: +1*object -1*scram' \
    -glt_label 3 object-scram \
    -float                                                                  \
    -jobs 8                                                                 \
    -fout -tout -x1D X.xmat.1D -xjpeg X.jpg                                 \
    -x1D_uncensored X.nocensore54.xmat.1D                                      \
    -bucket stats.${subj}
